# Generated by Django 6.0 on 2025-12-16 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
