# Generated by Django 6.0 on 2025-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
