# Generated by Django 6.0 on 2025-12-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_names_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='names',
        ),
        migrations.AddField(
            model_name='names',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='names',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='names',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
