# Generated by Django 6.0 on 2025-12-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_remove_names_names_names_first_name_names_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='names',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='names',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
