# Generated by Django 6.0 on 2025-12-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
